/**
 ******************************************************************************
 * @file           : mydisp.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Library body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>
#include <stdio.h>
#include "pinmap.h"
#include "main.h"

/** Functions ----------------------------------------------------------------*/
static void disp7seg_show_row3(int left, int center, int right);
static void disp7seg_show_row2(int left, int right);
static void disp7seg_show_segments(uint8_t A, uint8_t B, uint8_t C, uint8_t D, uint8_t E, uint8_t F, uint8_t G);

int __io_putchar(int ch)
{
    ITM_SendChar(ch);
    return ch;
}

static void disp7seg_show_row3(int left, int center, int right)
{
    printf ("\r\n");

    if (left | center)
        printf ("#");
    else
        printf(".");

    if (center)
        printf("#");
    else
        printf(".");

    if (center | right)
        printf("#");
    else
        printf(".");
}

static void disp7seg_show_row2(int left, int right)
{
    printf ("\r\n");

    if (left)
        printf ("# ");
    else
        printf(". ");
    if (right)
        printf("#");
    else
        printf(".");
}

static void disp7seg_show_segments(uint8_t A, uint8_t B, uint8_t C, uint8_t D, uint8_t E, uint8_t F, uint8_t G)
{
    disp7seg_show_row3(A, F, E);
    disp7seg_show_row2(A, E);
    disp7seg_show_row3(A | B, G, E | D);
    disp7seg_show_row2(B, D);
    disp7seg_show_row3(B, C, D);
    printf ("\r\n");
}


void mydispShow(void){
	uint8_t A; uint8_t B; uint8_t C; uint8_t D; uint8_t E; uint8_t F; uint8_t G;
	if(disp7seg_init_passed == 0)
	{
		printf("Los pines del display no estan inicializados\r\n");
		return;

	} else {
		if(HAL_GPIO_ReadPin(DISP_LED_PORT, DISP_SEG_A) == GPIO_PIN_SET) {A = 1;} else{A = 0;}
		if(HAL_GPIO_ReadPin(DISP_LED_PORT, DISP_SEG_B) == GPIO_PIN_SET) {B = 1;} else{B = 0;}
		if(HAL_GPIO_ReadPin(DISP_LED_PORT, DISP_SEG_C) == GPIO_PIN_SET) {C = 1;} else{C = 0;}
		if(HAL_GPIO_ReadPin(DISP_LED_PORT, DISP_SEG_D) == GPIO_PIN_SET) {D = 1;} else{D = 0;}
		if(HAL_GPIO_ReadPin(DISP_LED_PORT, DISP_SEG_E) == GPIO_PIN_SET) {E = 1;} else{E = 0;}
		if(HAL_GPIO_ReadPin(DISP_LED_PORT, DISP_SEG_F) == GPIO_PIN_SET) {F = 1;} else{F = 0;}
		if(HAL_GPIO_ReadPin(DISP_LED_PORT, DISP_SEG_G) == GPIO_PIN_SET) {G = 1;} else{G = 0;}
	}
		 disp7seg_show_segments(A,B,C,D,E,F,G);
}






